# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aaf8eafda45b4dacac284dbc05e85b9347492fcd445f8df9105cd2cc646444f5c16cb95af908813de789bac38ea0792f671f98c9ccd6d289b95d5b30b7ea882

test:
  secret_key_base: 2ff16b0c4c911436f6ff0d5c2be4f3f0965c1825efabd82cfa7f81db7746a4ae7bec9269174ea10c43421393dafc174cec471a348ae8b67642fe2caf363247af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
